package com.sgs.auth.model;

public enum UserRole {
    ROLE_NOT_PERMITTED_USER, ROLE_NOT_PERMITTED_ADMIN, ROLE_USER, ROLE_GROUP_ADMIN, ROLE_COMPANY_ADMIN, ROLE_ROOT_COMPANY_ADMIN, ROLE_SUPER_ADMIN
}
